### ISSUE TITLE
Add date range limits to the config file

### ISSUE THREAD

**Issue by simonhearne** [ncc-tools/pa-elasticsearch-coupler#2]
We should be able to configure a relative or absolute date limit in the past to collect only 'last 7 days' worth of data or data since a date. This is especially important for accounts that have been running for multiple years.

**Comment by guillaume-pasquet-ncc** [comment]
@simonhearne This would only be useful for the first import of data. Thereafter the coupler will only import new data since the first import, thereby negating the interest of using relative date/times.
